### ISSUE TITLE
API.createMenu

### ISSUE THREAD

**Issue by Dexelir** [Battlerax/MTGRP#1]
I would like to work on this project but this one problem gives me headaches. 

JS: 

API.createMenu(string title, string subtitle, double x, double y, int anchor, bool enableBanner = true); <--- in gt-mp
?; <--- in rage.mp

**Comment by Ahmad45123** [comment]
@Battlerax Is there an alternative to NativeUI menus in RageMp ?

**Comment by Dexelir** [comment]
> @Battlerax Is there an alternative to NativeUI menus in RageMp ?

I found it. Someone made a resource adding NativeUI menus to clientside js 👍
