### ISSUE TITLE
Error CS0579

### ISSUE THREAD

**Issue by hnomkeng** [Battlerax/MTGRP#3]
***OS : Windows 2012 Server
*VS Version : Enterprise 2017 15.9.12**

1>------ Rebuild All started: Project: mtgvrp, Configuration: Debug Any CPU ------
1>obj\Debug\netcoreapp2.2\mtgvrp.AssemblyInfo.cs(14,12,14,54): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
1>obj\Debug\netcoreapp2.2\mtgvrp.AssemblyInfo.cs(15,12,15,60): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
1>obj\Debug\netcoreapp2.2\mtgvrp.AssemblyInfo.cs(16,12,16,58): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
1>obj\Debug\netcoreapp2.2\mtgvrp.AssemblyInfo.cs(18,12,18,54): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
1>obj\Debug\netcoreapp2.2\mtgvrp.AssemblyInfo.cs(19,12,19,52): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
1>obj\Debug\netcoreapp2.2\mtgvrp.AssemblyInfo.cs(20,12,20,54): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
1>Done building project "mtgvrp.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Devotom** [comment]
Hi, 
Delete in mtgvp.AssemblyInfo.cs line 15,16,18,19,20

**Comment by Ahmad45123** [comment]
Please confirm if this issue has been fixed and close the issue.
